/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.idiomcentric

import kotlin.test.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val pattern = java.util.regex.Pattern.compile("some (?<houseNumber>[0-9]+) some")
        val matcher = pattern.matcher("some 4353543 some")
        matcher.find()
    }
}
